jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run: 'apt-get update && apt-get install -y gcc g++'
      - run: 'apt-get update && apt-get install -y cppcheck'
      - run: 'apt-get update && apt-get install -y valgrind'
      - run: 'apt-get update && sudo apt-get install -y cmake'
      - run: 'apt-get update && apt-get install -y gcovr'
      - run: 'apt-get update && apt-get install -y git'


      - run: ls -la && mkdir build && cd build &&
          cmake .. && ls -la
      - run: cmake --build build --target test_consecutive -- -j 6
      - run: cmake --build build --target test_parallel -- -j 6
      - run: cmake --build build --target C_HW2_TP_consecutive -- -j 6
      - run: cmake --build build --target C_HW2_TP_parallel -- -j 6


      - run:
          name: Start CppCheck
          command: 'ls -la && ls -la && cppcheck src/*  unit_tests/*'

      - run:
          name: Start main.c with static Library With Valgrind
          command: 'cd build && valgrind --leak-check=full --show-reachable=no ./C_HW2_TP_consecutive'

      - run:
          name: Start Tests Static Library With Valgrind
          command: 'cd build && valgrind ./test_consecutive --gtest_filter=* --gtest_color=no'

      - run:
          name: Start Tests Dynamic Library With Valgrind
          command: 'cd build && valgrind ./test_parallel --gtest_filter=* --gtest_color=no'


      - run:
          name: Gcovr
          command: 'gcovr -r .'
